# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccination', models.DateField(verbose_name='Date de vaccination')),
                ('type_vaccin', models.CharField(max_length=100, verbose_name='Type de vaccin')),
                ('nom_vaccin', models.CharField(max_length=100, verbose_name='Nom du vaccin')),
                ('dose_vaccin', models.FloatField(verbose_name='Dose administrée (mL)')),
                ('voie_administration', models.CharField(choices=[('Voie sous-cutanée', 'Voie sous-cutanée'), ('Voie orale', 'Voie orale'), ('Voie intramusculaire', 'Voie intramusculaire'), ('Voie intranasale', 'Voie intranasale')], max_length=30, verbose_name="Voie d'administration")),
                ('nom_veterinaire', models.CharField(max_length=100, verbose_name='Nom du vétérinaire')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('boucle_ovin', models.ForeignKey(help_text='Animal concerné par la vaccination', on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='troupeau.troupeau', verbose_name="Boucle de l'Ovin")),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-date_vaccination'],
                'indexes': [models.Index(fields=['boucle_ovin', 'date_vaccination'], name='vaccination_boucle__8d98de_idx')],
                'unique_together': {('boucle_ovin', 'date_vaccination')},
            },
        ),
    ]
