# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_alimentation', models.DateField(db_index=True, help_text='Jour où la ration a été donnée.', verbose_name="Date d'alimentation")),
                ('Type_Aliment', models.CharField(choices=[('Fourrage', 'Fourrage'), ('Foin', 'Foin'), ('Tourteau', 'Tourteau'), ('Son de mais', 'Son de maïs'), ('Concentré', 'Concentré'), ('Complément', 'Complément'), ('Eau', 'Eau'), ('Autre', 'Autre')], max_length=20, verbose_name="Type d'aliment")),
                ('Quantite_Kg', models.FloatField(help_text='Quantité totale distribuée ce jour-là (en kilogrammes).', verbose_name='Quantité (kg)')),
                ('Objectif', models.CharField(choices=[('Entretien', 'Entretien'), ('Gestation', 'Gestation'), ('Lactation', 'Lactation'), ('Croissance', 'Croissance'), ('Maladie', 'Maladie'), ('Autre', 'Autre')], max_length=20, verbose_name='Objectif')),
                ('Observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('Boucle_Ovin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentations', to='troupeau.troupeau', verbose_name='Animal (boucle)')),
            ],
            options={
                'verbose_name': 'Alimentation',
                'verbose_name_plural': 'Alimentations',
                'ordering': ['-Date_alimentation', '-id'],
                'indexes': [models.Index(fields=['Boucle_Ovin'], name='idx_alimentation_boucle')],
                'constraints': [models.UniqueConstraint(fields=('Boucle_Ovin', 'Date_alimentation'), name='unique_alimentation_per_day')],
            },
        ),
    ]
