# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genealogie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.FloatField(default=0.0, help_text="Stocké en base (0..1), recalculé automatiquement à l'enregistrement.", verbose_name='Coefficient de consanguinité (Fa)')),
                ('agneau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genealogie', to='troupeau.troupeau', verbose_name='Agneau (boucle)')),
                ('mere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genealogies_comme_mere', to='troupeau.troupeau', verbose_name='Mère (boucle)')),
                ('pere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genealogies_comme_pere', to='troupeau.troupeau', verbose_name='Père (boucle)')),
            ],
            options={
                'verbose_name': 'Généalogie',
                'verbose_name_plural': 'Généalogies',
                'db_table': 'genealogie',
                'indexes': [models.Index(fields=['agneau'], name='genealogie_agneau__cb49a4_idx'), models.Index(fields=['mere'], name='genealogie_mere_id_908724_idx'), models.Index(fields=['pere'], name='genealogie_pere_id_397d6c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('agneau', models.F('mere')), _negated=True), name='genealogie_agneau_diff_mere'), models.CheckConstraint(condition=models.Q(('agneau', models.F('pere')), _negated=True), name='genealogie_agneau_diff_pere'), models.CheckConstraint(condition=models.Q(('mere', models.F('pere')), _negated=True), name='genealogie_mere_diff_pere')],
            },
        ),
    ]
