# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accouplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_lutte', models.DateField(verbose_name='Début de lutte')),
                ('date_fin_lutte', models.DateField(blank=True, null=True, verbose_name='Fin de lutte')),
                ('date_verification_gestation', models.DateField(blank=True, null=True, verbose_name='Vérification gestation')),
                ('date_gestation', models.DateField(blank=True, null=True, verbose_name='Date de gestation')),
                ('observations', models.TextField(blank=True, null=True)),
                ('accouplement_reussi', models.BooleanField(default=False, editable=False)),
                ('boucle_belier', models.ForeignKey(limit_choices_to={'boucle_active': True, 'sexe': 'male'}, on_delete=django.db.models.deletion.CASCADE, related_name='accouplements_comme_belier', to='troupeau.troupeau', verbose_name='Bélier')),
                ('boucle_brebis', models.ForeignKey(limit_choices_to={'boucle_active': True, 'sexe': 'femelle'}, on_delete=django.db.models.deletion.CASCADE, related_name='accouplements_comme_brebis', to='troupeau.troupeau', verbose_name='Brebis')),
            ],
            options={
                'verbose_name': 'Accouplement',
                'verbose_name_plural': 'Accouplements',
                'ordering': ['-date_debut_lutte'],
                'indexes': [models.Index(fields=['boucle_brebis'], name='accouplemen_boucle__4efa52_idx'), models.Index(fields=['boucle_belier'], name='accouplemen_boucle__2be442_idx'), models.Index(fields=['date_debut_lutte'], name='accouplemen_date_de_bd66d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('boucle_belier', 'boucle_brebis', 'date_debut_lutte'), name='uniq_couple_debut_lutte')],
            },
        ),
    ]
