# Generated by Django 5.2.4 on 2025-08-23 07:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gestation', models.DateField(default=datetime.date.today, verbose_name='Date de gestation')),
                ('methode_confirmation', models.CharField(choices=[('Palpation', 'Palpation'), ('Echographie', 'Échographie'), ('Observation comportementale', 'Observation comportementale')], max_length=30, verbose_name='Méthode de confirmation')),
                ('etat_gestation', models.CharField(choices=[('Confirmée', 'Confirmée'), ('Non Confirmée', 'Non Confirmée'), ('A surveiller', 'À surveiller')], max_length=30, verbose_name='État de gestation')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('boucle_brebis', models.ForeignKey(limit_choices_to={'boucle_active': True, 'sexe': 'femelle'}, on_delete=django.db.models.deletion.CASCADE, to='troupeau.troupeau', verbose_name='Brebis')),
            ],
            options={
                'verbose_name': 'Gestation',
                'verbose_name_plural': 'Gestations',
                'ordering': ['-date_gestation'],
                'indexes': [models.Index(fields=['boucle_brebis'], name='gestation_g_boucle__a151bd_idx'), models.Index(fields=['date_gestation'], name='gestation_g_date_ge_2472c9_idx')],
                'unique_together': {('boucle_brebis', 'date_gestation')},
            },
        ),
    ]
