# Generated by Django 5.2.4 on 2025-10-26 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestation', '0001_initial'),
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestation',
            options={'ordering': ['-date_gestation', '-id'], 'verbose_name': 'Gestation', 'verbose_name_plural': 'Gestations'},
        ),
        migrations.AlterUniqueTogether(
            name='gestation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='date_gestation',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date de gestation'),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='etat_gestation',
            field=models.CharField(choices=[('Confirmée', 'Confirmée'), ('Non Confirmée', 'Non Confirmée'), ('A surveiller', 'À surveiller')], db_index=True, max_length=30, verbose_name='État de gestation'),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='methode_confirmation',
            field=models.CharField(choices=[('Palpation', 'Palpation'), ('Echographie', 'Échographie'), ('Observation comportementale', 'Observation comportementale')], db_index=True, max_length=30, verbose_name='Méthode de confirmation'),
        ),
        migrations.AddIndex(
            model_name='gestation',
            index=models.Index(fields=['etat_gestation'], name='gestation_g_etat_ge_cdc0aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='gestation',
            constraint=models.UniqueConstraint(fields=('boucle_brebis', 'date_gestation'), name='uniq_gestation_brebis_jour'),
        ),
    ]
