# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maladie', '0001_initial'),
        ('troupeau', '0001_initial'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('nom_veterinaire', models.CharField(max_length=100)),
                ('motif_de_la_visite', models.CharField(choices=[('Diagnostic et traitement des maladies', 'Diagnostic et traitement des maladies'), ('Vaccinations préventives', 'Vaccinations préventives'), ('Suivi des cas chroniques ou graves', 'Suivi des cas chroniques ou graves'), ('Assistance lors des avortements ou troubles de la reproduction', 'Assistance lors des avortements ou troubles de la reproduction'), ('Interventions chirurgicales ou urgentes', 'Interventions chirurgicales ou urgentes'), ('Contrôles sanitaires réglementaires', 'Contrôles sanitaires réglementaires'), ("Évaluation de l'état général du troupeau", "Évaluation de l'état général du troupeau"), ('Prescriptions de médicaments', 'Prescriptions de médicaments')], max_length=100)),
                ('traitement_effectue', models.CharField(choices=[('Identification des pathologies et prescription de médicaments adaptés', 'Identification des pathologies et prescription de médicaments adaptés'), ('Protection contre la brucellose, fièvre catarrhale', 'Protection contre la brucellose, fièvre catarrhale'), ('Surveillance des animaux atteints de maladies persistantes', 'Surveillance des animaux atteints de maladies persistantes'), ('Traitement des avortements, infertilités, rétentions placentaires', 'Traitement des avortements, infertilités, rétentions placentaires'), ('Intervention sur plaies, abcès ou boiteries sévères', 'Intervention sur plaies, abcès ou boiteries sévères'), ("Vérification lors des ventes, abattages ou transports d'ovins", "Vérification lors des ventes, abattages ou transports d'ovins"), ('Analyse générale pour améliorer nutrition, reproduction ou bien-être', 'Analyse générale pour améliorer nutrition, reproduction ou bien-être'), ('Certains produits sont strictement délivrés par un vétérinaire', 'Certains produits sont strictement délivrés par un vétérinaire')], max_length=150)),
                ('recommandations', models.TextField()),
                ('cout_visite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observations', models.TextField(blank=True, null=True)),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maladie.maladie')),
                ('troupeau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troupeau.troupeau')),
                ('vaccination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccination.vaccination')),
            ],
            options={
                'verbose_name': 'Visite vétérinaire',
                'verbose_name_plural': 'Visites vétérinaires',
                'ordering': ['-date_visite'],
                'indexes': [models.Index(fields=['date_visite'], name='veterinaire_date_vi_48df4a_idx'), models.Index(fields=['nom_veterinaire'], name='veterinaire_nom_vet_fa2d01_idx'), models.Index(fields=['troupeau'], name='veterinaire_troupea_82d1cc_idx')],
                'unique_together': {('date_visite', 'nom_veterinaire', 'troupeau')},
            },
        ),
    ]
