# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Croissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_mesure', models.DateField()),
                ('Poids_Kg', models.FloatField()),
                ('Taille_CM', models.FloatField()),
                ('Etat_Sante', models.CharField(choices=[('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais'), ('Malade', 'Malade')], max_length=20)),
                ('Croissance_Evaluation', models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Retard de croissance', 'Retard de croissance'), ('Croissance accélérée', 'Croissance accélérée')], max_length=30, null=True)),
                ('Age_en_Mois', models.PositiveIntegerField(blank=True, null=True)),
                ('Observations', models.TextField(blank=True)),
                ('est_historique', models.BooleanField(default=False)),
                ('Boucle_Ovin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='croissances', to='troupeau.troupeau')),
            ],
            options={
                'verbose_name': 'Suivi de croissance',
                'verbose_name_plural': 'Suivis de croissance',
                'ordering': ['-Date_mesure'],
                'unique_together': {('Boucle_Ovin', 'Date_mesure', 'est_historique')},
            },
        ),
    ]
