# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_observation', models.DateField(help_text="Date d'apparition des symptômes")),
                ('Date_guerison', models.DateField(blank=True, help_text='Date de disparition des symptômes', null=True)),
                ('Symptomes_Observes', models.CharField(choices=[('Fièvre', 'Fièvre'), ('Amaigrissement', 'Amaigrissement'), ('Anorexie', 'Anorexie'), ('Diarrhée', 'Diarrhée'), ('Jetage nasal', 'Jetage nasal'), ('Jetage oculaire', 'Jetage oculaire'), ('Toux', 'Toux'), ('Dyspnée', 'Dyspnée'), ('Boiterie', 'Boiterie'), ('Marche en cercle', 'Marche en cercle'), ('Paralysie', 'Paralysie'), ('Cécité', 'Cécité'), ('Tremblements', 'Tremblements'), ('Convulsions', 'Convulsions'), ('Ulcérations buccales', 'Ulcérations buccales'), ('Croûtes cutanées', 'Croûtes cutanées'), ('Œdème de la tête', 'Œdème de la tête'), ('Œdème sous-glossien', 'Œdème sous-glossien'), ('Perte de laine', 'Perte de laine'), ('Hyperesthésie', 'Hyperesthésie'), ('Comportement agité', 'Comportement agité'), ('Avortement', 'Avortement'), ('Rétention placentaire', 'Rétention placentaire'), ('Baisse de fertilité', 'Baisse de fertilité'), ('Dermatite', 'Dermatite'), ('Conjonctivite', 'Conjonctivite'), ('Cachexie', 'Cachexie')], max_length=50)),
                ('Nom_Maladie', models.CharField(choices=[('Peste des petits ruminants', 'Peste des petits ruminants'), ('Clavelée', 'Clavelée'), ('Brucellose', 'Brucellose'), ('Pasteurellose', 'Pasteurellose'), ('Strongyloses digestives', 'Strongyloses digestives'), ('Fasciolose', 'Fasciolose'), ('Oestrose', 'Oestrose'), ('Coenurose', 'Coenurose'), ('Toxémie de gestation', 'Toxémie de gestation'), ('Hypocalcémie', 'Hypocalcémie'), ('Carence en cuivre', 'Carence en cuivre'), ('Fièvre catarrhale ovine', 'Fièvre catarrhale ovine'), ('Ecthyma contagieux', 'Ecthyma contagieux')], max_length=50)),
                ('Traitement_Administre', models.CharField(blank=True, choices=[('Antibiotique', 'Antibiotique'), ('Antiparasitaire', 'Antiparasitaire'), ('Antipyrétique', 'Antipyrétique'), ('Vermifuge', 'Vermifuge'), ('Sérum injectable', 'Sérum injectable'), ('Vaccin', 'Vaccin'), ('Supplément minéral', 'Supplément minéral'), ('Hydratation IV', 'Hydratation IV'), ('Antifongique', 'Antifongique'), ('Chirurgie locale', 'Chirurgie locale'), ('Nettoyage des plaies', 'Nettoyage des plaies'), ('Traitement symptomatique', 'Traitement symptomatique')], max_length=50, null=True)),
                ('Duree_Traitement', models.PositiveIntegerField(blank=True, help_text='Durée en jours', null=True)),
                ('Cout_Traitement_FCFA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gravite', models.CharField(blank=True, choices=[('Léger', 'Léger'), ('Modéré', 'Modéré'), ('Grave', 'Grave'), ('Critique', 'Critique')], max_length=20, null=True)),
                ('Statut', models.CharField(choices=[('Actif', 'Actif'), ('Résolu', 'Résolu'), ('Chronique', 'Chronique')], default='Actif', max_length=20)),
                ('Veterinaire', models.CharField(max_length=100)),
                ('Observations', models.TextField(blank=True, null=True)),
                ('Boucle_Ovin', models.ForeignKey(help_text="Sélectionnez l'ovin concerné", on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='troupeau.troupeau')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['-Date_observation'],
                'indexes': [models.Index(fields=['Boucle_Ovin'], name='maladie_mal_Boucle__fd9047_idx'), models.Index(fields=['Date_observation'], name='maladie_mal_Date_ob_8df658_idx'), models.Index(fields=['Nom_Maladie'], name='maladie_mal_Nom_Mal_7bdd30_idx')],
                'unique_together': {('Boucle_Ovin', 'Nom_Maladie', 'Date_observation', 'Symptomes_Observes', 'Traitement_Administre')},
            },
        ),
    ]
