# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accouplement', '0001_initial'),
        ('gestation', '0001_initial'),
        ('naissance', '0001_initial'),
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('accouplement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction', to='accouplement.accouplement', verbose_name='Accouplement')),
                ('femelle', models.ForeignKey(limit_choices_to={'sexe': 'femelle'}, on_delete=django.db.models.deletion.CASCADE, related_name='reproductions_femelle', to='troupeau.troupeau', verbose_name='Femelle')),
                ('gestation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction', to='gestation.gestation', verbose_name='Gestation')),
                ('male', models.ForeignKey(blank=True, limit_choices_to={'sexe': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproductions_male', to='troupeau.troupeau', verbose_name='Mâle')),
                ('naissance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction', to='naissance.naissance', verbose_name='Naissance')),
            ],
            options={
                'verbose_name': 'Cycle de reproduction',
                'verbose_name_plural': 'Cycles de reproduction',
                'ordering': ['-accouplement__date_debut_lutte'],
                'indexes': [models.Index(fields=['femelle'], name='reproductio_femelle_502a1f_idx'), models.Index(fields=['male'], name='reproductio_male_id_b9ce39_idx')],
            },
        ),
    ]
