# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historiquetroupeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateField()),
                ('statut', models.CharField(choices=[('Création', 'Création'), ('Modification', 'Modification'), ('Suppression', 'Suppression'), ('Naissance', 'Naissance'), ('Vendu', 'Vendu'), ('Décédé', 'Décédé'), ('Sortie', 'Sortie'), ('Prêt notre ferme', 'Prêt notre ferme'), ('Prêt autre ferme', 'Prêt autre ferme'), ('Échange Ovin', 'Échange Ovin'), ('Achat', 'Achat'), ('Soin', 'Soin')], max_length=30)),
                ('ancienne_boucle', models.CharField(blank=True, max_length=20, null=True)),
                ('ancienne_naissance_date', models.DateField(blank=True, null=True)),
                ('ancienne_boucle_active', models.BooleanField(blank=True, null=True)),
                ('ancien_proprietaire', models.CharField(blank=True, max_length=50, null=True)),
                ('ancienne_origine', models.CharField(blank=True, max_length=50, null=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('ancien_sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('ancienne_race', models.CharField(blank=True, max_length=50, null=True)),
                ('ancienne_achat_date', models.DateField(blank=True, null=True)),
                ('ancienne_entree_date', models.DateField(blank=True, null=True)),
                ('ancienne_date_sortie', models.DateField(blank=True, null=True)),
                ('nouvelle_boucle', models.CharField(blank=True, max_length=20, null=True)),
                ('nouvelle_naissance_date', models.DateField(blank=True, null=True)),
                ('nouvelle_boucle_active', models.BooleanField(blank=True, null=True)),
                ('nouveau_proprietaire', models.CharField(blank=True, max_length=50, null=True)),
                ('nouvelle_origine', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('nouvelle_race', models.CharField(blank=True, max_length=50, null=True)),
                ('nouvelle_achat_date', models.DateField(blank=True, null=True)),
                ('nouvelle_entree_date', models.DateField(blank=True, null=True)),
                ('nouvelle_date_sortie', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('troupeau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='troupeau.troupeau')),
            ],
            options={
                'verbose_name': 'Historique du Troupeau',
                'verbose_name_plural': 'Historique des Troupeaux',
                'db_table': 'historiquetroupeau',
                'ordering': ['-date_evenement'],
                'indexes': [models.Index(fields=['troupeau'], name='historiquet_troupea_f718fc_idx'), models.Index(fields=['date_evenement'], name='historiquet_date_ev_e5ef69_idx'), models.Index(fields=['statut'], name='historiquet_statut_25b2d2_idx')],
            },
        ),
    ]
