# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accouplement', '0001_initial'),
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine_accouplement', models.CharField(choices=[('Interne', 'Interne (dans la ferme)'), ('Externe', 'Externe (hors ferme)'), ('Inconnu', 'Inconnu')], default='Inconnu', max_length=20, verbose_name='Origine de l’accouplement')),
                ('nom_male_externe', models.CharField(blank=True, help_text='Nom ou boucle du mâle si accouplement externe', max_length=50, null=True, verbose_name='Mâle externe (si externe)')),
                ('date_mise_bas', models.DateField(verbose_name='Date de mise-bas')),
                ('observations', models.TextField(blank=True, null=True)),
                ('accouplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naissances', to='accouplement.accouplement', verbose_name='Accouplement (si interne)')),
                ('boucle_mere', models.ForeignKey(limit_choices_to={'boucle_active': True, 'sexe': 'femelle'}, on_delete=django.db.models.deletion.CASCADE, related_name='naissances', to='troupeau.troupeau', verbose_name='Mère (boucle)')),
            ],
            options={
                'verbose_name': 'Naissance',
                'verbose_name_plural': 'Naissances',
                'db_table': 'naissance',
                'ordering': ['-date_mise_bas'],
            },
        ),
        migrations.CreateModel(
            name='Agneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('male', 'Mâle'), ('femelle', 'Femelle')], max_length=7)),
                ('boucle', models.OneToOneField(limit_choices_to={'statut': 'naissance'}, on_delete=django.db.models.deletion.CASCADE, related_name='enregistrement_agneau', to='troupeau.troupeau', verbose_name='Boucle de l’agneau')),
                ('naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agneaux', to='naissance.naissance', verbose_name='Naissance')),
            ],
            options={
                'verbose_name': 'Agneau',
                'verbose_name_plural': 'Agneaux',
                'db_table': 'agneau',
            },
        ),
        migrations.AddConstraint(
            model_name='naissance',
            constraint=models.UniqueConstraint(fields=('boucle_mere', 'date_mise_bas'), name='uniq_naissance_mere_date'),
        ),
    ]
